---
- name: Ensuring that Apache is installed
  apt: 
    name=apache2 
    state=latest
    update_cache=yes
    cache_valid_time=600

- name: Ensuring that required Apache mods are enabled
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite
    - speling

- name: Add wikipedia aliases to /etc/hosts
  lineinfile: 
    dest=/etc/hosts 
    line="127.0.0.1 wikipedia www.wikipedia.org en.wikipedia.org wikipedia.org"
    regexp="^[^#].*wikipedia.org.*"
#- name: Install tunapanda-wikipedia
#  apt: name=tunapanda-wikipedia state=latest update_cache=yes force=yes
- name: Creating Apache config
  template:
      src="httpd-wikipedia.j2"
      dest="{{ apache_dir }}/sites-available/tunapanda-wikipedia"

- name: Linking Apache config
  file: 
    src:  "{{ apache_dir }}/sites-available/tunapanda-wikipedia" 
    path: "{{ apache_dir }}/sites-enabled/tunapanda-wikipedia"
    state: link
  notify:
    - restart apache

- name: Creating document root
  file:
    path: "{{ wikipedia__provision__base_dir }}"
    state: "directory"
    owner: "{{ apache_user }}"

- name: Creating 404 page
  template:
    src="notfound.html.j2"
    dest="{{ wikipedia__provision__base_dir }}/notfound.html"

- name: Linking Apache document root
  file: 
    src:  "{{ wikipedia__provision__base_dir }}" 
    path: "{{ apache_docroot }}/wikipedia"
    state: link
    
- name: Creating data dir {{ wikipedia__provision__base_dir }}
  file: path={{ wikipedia__provision__base_dir }} state=directory

- name: Checking mount status of {{ wikipedia__provision__base_dir }}
  shell: mount | grep {{ wikipedia__provision__base_dir }}
  register: is_mounted
  ignore_errors: True
  
#- name: Mounting {{ wikipedia__provision__base_dir }}
#  command: mount --bind {{ vagrant_share }}/playbooks/roles/wikipedia/data {{ wikipedia__provision__base_dir }}
#  when: is_mounted|failed
